networks:
  squiglink:
    name: squiglink

services:
  postgres:
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${SQUIGLINK_POSTGRES_PASSWORD}
      POSTGRES_USER: ${SQUIGLINK_POSTGRES_USER}
    healthcheck:
      interval: 10s
      retries: 5
      test: ["CMD-SHELL", "pg_isready -U ${SQUIGLINK_POSTGRES_USER}"]
      timeout: 5s
    image: postgres:18.1-alpine3.23
    networks:
      - squiglink
    ports:
      - 5432:5432

  server:
    build:
      context: .
      target: development
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - squiglink
    ports:
      - 3000:3000
    volumes:
      - ./node_modules:/server/node_modules
      - .:/server
