dotenv:
  - .env

tasks:
  check:
    desc: Check everything.
    cmds:
      - task: check-formatting
      - task: check-linting
      - task: check-tests
      - task: check-types

  check-formatting:
    desc: Check formatting.
    cmds:
      - docker compose run --rm server pnpm oxfmt --check {{.CLI_ARGS}}

  check-linting:
    desc: Check linting.
    cmds:
      - docker compose run --rm server pnpm oxlint --deny-warnings {{.CLI_ARGS}}

  check-tests:
    desc: Check tests.
    cmds:
      - docker compose run --rm server pnpm vitest run {{.CLI_ARGS}}

  check-types:
    desc: Check types.
    cmds:
      - docker compose run --rm server pnpm tsc --noEmit {{.CLI_ARGS}}

  database-create:
    desc: Create the database.
    cmds:
      - docker compose run
        --env PGPASSWORD={{.SQUIGLINK_POSTGRES_PASSWORD}}
        --rm
        postgres
        psql
        --command="CREATE DATABASE {{.SQUIGLINK_POSTGRES_DATABASE}};"
        --dbname=postgres
        --host=postgres
        --username={{.SQUIGLINK_POSTGRES_USER}}

  database-create-test:
    desc: Create the test database.
    cmds:
      - docker compose run
        --env PGPASSWORD={{.SQUIGLINK_POSTGRES_PASSWORD}}
        --rm
        postgres
        psql
        --command="CREATE DATABASE {{.SQUIGLINK_POSTGRES_TEST_DATABASE}};"
        --dbname=postgres
        --host=postgres
        --username={{.SQUIGLINK_POSTGRES_USER}}

  fix-formatting:
    desc: Fix formatting.
    cmds:
      - docker compose run --rm server pnpm oxfmt --write {{.CLI_ARGS}}

  generate-openapi-specification:
    desc: Generate the OpenAPI specification.
    cmds:
      - docker compose run --rm server pnpm tsx scripts/generate-openapi.ts

  install-dependencies:
    desc: Install dependencies.
    cmds:
      - docker compose run --rm server pnpm install

  kysely:
    desc: Execute a Kysely command against the database.
    cmds:
      - docker compose run --rm server pnpm kysely {{.CLI_ARGS}}

  kysely-generate-types:
    desc: Generate Kysely types from the database.
    cmds:
      - docker compose run --rm server pnpm kysely-codegen
      - docker compose run --rm
        server
        sed
        --in-place 's/export interface DB/export interface Database/'
        source/types.ts
      - task: fix-formatting
        vars:
          CLI_ARGS: source/types.ts

  kysely-test:
    desc: Execute a Kysely command against the test database.
    cmds:
      - docker compose run
        --env SQUIGLINK_POSTGRES_DATABASE="{{.SQUIGLINK_POSTGRES_TEST_DATABASE}}"
        --rm
        server
        pnpm kysely {{.CLI_ARGS}}

  list:
    aliases:
      - default
    desc: List available tasks.
    cmds:
      - task --list

  setup:
    desc: Setup the application.
    cmds:
      - task: install-dependencies
      - task: database-create
      - task: database-create-test
      - task: kysely
        vars:
          CLI_ARGS: migrate:latest
      - task: kysely-test
        vars:
          CLI_ARGS: migrate:latest
      - task: kysely
        vars:
          CLI_ARGS: seed run

  start:
    desc: Start the application.
    cmds:
      - docker compose up

version: 3
